[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "phpPackages.pcov", "phpPackages.php-cs-fixer", "phpPackages.phpstan", "phpPackages.phpunit", "phpPackages.phpmyadmin", "mysql", "nginx"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan config:clear",
  "php artisan view:clear",
  "php artisan route:clear",
  "php artisan key:generate"
]

[phases.start]
cmd = "php artisan serve --host=0.0.0.0 --port=24344"
